language: python

python:
  - "3.6.4"

before_install:
  - sudo apt-get update

install:
  - pip install codecov
  - pip install -r requirements.txt

virtualenv:
  system_site_package: true

script:
  - coverage run test.py

after_success:
  - codecov
