language: python

python:
  - "3.6.1"

before_install:
  - sudo apt-get update

install:
  - pip install codecov
  - pip install -r requirements.txt

virtualenv:
  system_site_package: true
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - coverage run test.py

after_success:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --prefix `pwd` --input-type coverage.py coverage.xml
  - codecov
