"""Module used to test dota_wiki_parser module methods."""

import json
import unittest

from wiki_parser import wiki_parser as parser

__author__ = 'Jonarzz'


class WikiParserTest(unittest.TestCase):
    """Class used to test dota_wiki_parser module.
    Inherits from TestCase class of unittest module.
    """

    def test_pages_to_parse(self):
        """Method testing pages_to_parse method from dota_wiki_parser module.

        The method checks if the requested response is consists of JSON payload as expected.
        """

        url = parser.URL_DOMAIN + parser.API_PATH + parser.CATEGORY
        parsed_json = json.loads(parser.page_to_parse(url))

        self.assertIsNotNone(parsed_json)
        category_members = parsed_json["query"]["categorymembers"]
        self.assertNotEqual(category_members, [])
        self.assertTrue(len(category_members) > 150)
        self.assertEqual(category_members[0]['title'], 'Abaddon/Responses')
        self.assertEqual(category_members[-1]['title'], 'Zeus/Responses')

    def test_pages_for_category(self):
        """Method testing pages_for_category method from dota_wiki_parser module.

        The method checks if the list generated by the method is not empty.
        """
        self.assertNotEqual(parser.pages_for_category(parser.CATEGORY), [])

    def test_clean_key(self):
        """Method testing clean_key method from dota_wiki_parser module.

        Please, check help for clean_key method for further information about the expected results.
        """
        self.assertEqual(parser.clean_key('   Earthshaker  !  '), 'earthshaker')

    def test_value_from_element(self):
        """Method testing value_from_element method from dota_wiki_parser module.

        The module is testing if the method extracts a proper url from the given html element.
        """
        url = '<ul><li><span><audio hidden="" class="ext-audiobutton" data-volume="1.0"><source ' \
              'src="https://gamepedia.cursecdn.com/dota2_gamepedia/8/8c/Ratt_level_01.mp3" type="audio/mpeg" /><a ' \
              'href="https://gamepedia.cursecdn.com/dota2_gamepedia/8/8c/Ratt_level_01.mp3">Link</a></audio><a ' \
              'class="ext-audiobutton" data-state="play" title="Play/Pause">▶️</a></span> Ratchet up the trap!</li> '
        self.assertEqual(parser.link_from_element(url),
                         '"https://gamepedia.cursecdn.com/dota2_gamepedia/8/8c/Ratt_level_01.mp3')
